# Generated by Django 3.0.4 on 2020-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timeRegistered',
            field=models.DateTimeField(),
        ),
    ]
