# Generated by Django 3.0.4 on 2020-03-29 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200329_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timeRegistered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
