# Generated by Django 3.0.4 on 2020-03-29 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200329_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timeRegistered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
