<<<<<<< HEAD
# Generated by Django 3.0.4 on 2020-04-12 17:30
=======
# Generated by Django 2.2 on 2020-04-13 00:57
>>>>>>> jecanizarez

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
