# Generated by Django 2.2 on 2020-05-11 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=20)),
                ('historial', models.CharField(default='{}', max_length=200)),
                ('voluntariado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voluntariados.Voluntariado')),
                ('voluntario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Voluntario')),
            ],
        ),
    ]
