# Generated by Django 3.0.4 on 2020-05-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='historial',
            field=models.CharField(default='{}', max_length=200),
        ),
    ]
