# Generated by Django 2.2 on 2020-04-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0001_initial'),
        ('postulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fecha',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulacion',
            name='voluntariado',
            field=models.ForeignKey(default=None, on_delete=None, to='voluntariados.Voluntariado'),
            preserve_default=False,
        ),
    ]
