# Generated by Django 3.0.4 on 2020-04-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntariados', '0001_initial'),
        ('postulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='voluntariado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariados.Voluntariado'),
        ),
    ]
