# Generated by Django 2.2 on 2020-04-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0002_auto_20200413_1242'),
        ('postulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='voluntariado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariados.Voluntariado'),
        ),
    ]
