# Generated by Django 2.2 on 2020-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0002_auto_20200411_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
