# Generated by Django 3.0.4 on 2020-05-11 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0001_initial'),
        ('usuarios', '0002_remove_voluntario_postulaciones'),
        ('postulacion', '0002_postulacion_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='voluntario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Voluntario'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 17, 28, 24, 10048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='voluntariado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voluntariados.Voluntariado'),
        ),
    ]
