# Generated by Django 3.0.4 on 2020-05-11 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0003_auto_20200511_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
