# Generated by Django 2.2 on 2020-04-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0003_auto_20200411_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='voluntariado',
            field=models.ForeignKey(null=True, on_delete=None, to='voluntariados.Voluntariado'),
        ),
    ]
