# Generated by Django 2.2 on 2020-04-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0005_auto_20200411_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='voluntariado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariados.Voluntariado'),
        ),
    ]
