# Generated by Django 2.2 on 2020-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=20)),
            ],
        ),
    ]
