# Generated by Django 2.2 on 2020-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0002_auto_20200413_1242'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='voluntariados',
            field=models.ManyToManyField(blank=True, to='voluntariados.Voluntariado'),
        ),
    ]
