# Generated by Django 2.2 on 2020-04-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='imagen',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
