# Generated by Django 3.0.4 on 2020-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntariados', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='voluntariados',
            field=models.ManyToManyField(blank=True, to='voluntariados.Voluntariado'),
        ),
    ]
