# Generated by Django 3.0.4 on 2020-05-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='postulaciones',
        ),
    ]
