# Generated by Django 2.2 on 2020-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_voluntario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='imagen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
