# Generated by Django 3.0.4 on 2020-04-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0001_initial'),
        ('usuarios', '0002_ong_voluntariados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='gustos',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='idiomas',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='postulaciones',
        ),
        migrations.AlterField(
            model_name='ong',
            name='voluntariados',
            field=models.ManyToManyField(blank=True, to='voluntariados.Voluntariado'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='imagen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
