# Generated by Django 2.2 on 2020-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200412_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='postulaciones',
            field=models.ManyToManyField(blank=True, to='postulacion.Postulacion'),
        ),
    ]
