# Generated by Django 3.0.4 on 2020-05-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_voluntario_postulaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='voluntariados',
        ),
    ]
