# Generated by Django 2.2 on 2020-04-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intereses', '0001_initial'),
        ('usuarios', '0002_auto_20200411_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('pais', models.CharField(max_length=25)),
                ('ocuacion', models.CharField(max_length=30)),
                ('idiomas', models.ForeignKey(on_delete=None, to='intereses.Idioma')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
