# Generated by Django 2.2 on 2020-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intereses', '0001_initial'),
        ('usuarios', '0003_ong_voluntario'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='gustos',
            field=models.ForeignKey(default=None, on_delete=None, to='intereses.Gusto'),
            preserve_default=False,
        ),
    ]
