# Generated by Django 2.2 on 2020-04-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200412_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voluntario',
        ),
    ]
