# Generated by Django 2.2 on 2020-04-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200427_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
