# Generated by Django 2.2 on 2020-04-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0001_initial'),
        ('intereses', '0001_initial'),
        ('usuarios', '0004_delete_voluntario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='voluntariados',
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('pais', models.CharField(max_length=25)),
                ('ocupacion', models.CharField(max_length=30)),
                ('gustos', models.ManyToManyField(to='intereses.Gusto')),
                ('idiomas', models.ManyToManyField(to='intereses.Idioma')),
                ('postulaciones', models.ManyToManyField(blank=True, to='postulacion.Postulacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
