# Generated by Django 2.2 on 2020-04-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0002_auto_20200411_1708'),
        ('usuarios', '0004_voluntario_gustos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntario',
            old_name='ocuacion',
            new_name='ocupacion',
        ),
        migrations.AddField(
            model_name='ong',
            name='voluntariados',
            field=models.ForeignKey(default=None, on_delete=None, to='usuarios.Voluntario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='postulaciones',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='postulacion.Postulacion'),
            preserve_default=False,
        ),
    ]
