# Generated by Django 2.2 on 2020-04-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intereses', '0001_initial'),
        ('usuarios', '0005_auto_20200411_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='idiomas',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='idiomas',
            field=models.ManyToManyField(to='intereses.Idioma'),
        ),
    ]
