# Generated by Django 2.2 on 2020-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intereses', '0002_auto_20200411_1910'),
        ('postulacion', '0003_auto_20200411_1910'),
        ('usuarios', '0006_auto_20200411_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='voluntariados',
        ),
        migrations.AddField(
            model_name='ong',
            name='voluntariados',
            field=models.ManyToManyField(to='usuarios.Voluntario'),
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='gustos',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='gustos',
            field=models.ManyToManyField(to='intereses.Gusto'),
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='postulaciones',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='postulaciones',
            field=models.ManyToManyField(to='postulacion.Postulacion'),
        ),
    ]
