# Generated by Django 2.2 on 2020-04-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200411_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='voluntariados',
            field=models.ManyToManyField(to='voluntariados.Voluntariado'),
        ),
    ]
