# Generated by Django 2.2 on 2020-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Califiacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=100)),
            ],
        ),
    ]
