# Generated by Django 2.2 on 2020-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=20)),
                ('duracion', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=25)),
                ('precio', models.FloatField()),
                ('requsitos', models.CharField(max_length=50)),
            ],
        ),
    ]
