# Generated by Django 3.0.2 on 2020-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('intereses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=20)),
                ('duracion', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=25)),
                ('precio', models.FloatField()),
                ('calificaciones', models.ManyToManyField(to='calificaciones.Calificacion')),
                ('gustosRequeridos', models.ManyToManyField(to='intereses.Gusto')),
                ('idiomasRequeridos', models.ManyToManyField(to='intereses.Idioma')),
            ],
        ),
    ]
