# Generated by Django 2.2 on 2020-04-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntariado',
            name='descripcion',
        ),
    ]
