# Generated by Django 3.0.4 on 2020-05-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_ong_voluntariados'),
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntariado',
            name='organizacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ONG'),
        ),
    ]
