# Generated by Django 2.2 on 2020-04-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntariado',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='imagen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='lugar',
            field=models.CharField(max_length=50),
        ),
    ]
