# Generated by Django 2.2 on 2020-04-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_auto_20200411_1708'),
        ('intereses', '0001_initial'),
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntariado',
            name='calificaciones',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calificaciones.Calificacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='gustosRequeridos',
            field=models.ForeignKey(default=None, on_delete=None, to='intereses.Gusto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='idiomasRequeridos',
            field=models.ForeignKey(default=None, on_delete=None, to='intereses.Idioma'),
            preserve_default=False,
        ),
    ]
