# Generated by Django 2.2 on 2020-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intereses', '0002_auto_20200411_1910'),
        ('calificaciones', '0003_auto_20200411_1910'),
        ('voluntariados', '0002_auto_20200411_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntariado',
            name='requsitos',
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='calificaciones',
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='calificaciones',
            field=models.ManyToManyField(to='calificaciones.Calificacion'),
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='gustosRequeridos',
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='gustosRequeridos',
            field=models.ManyToManyField(to='intereses.Gusto'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='idiomasRequeridos',
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='idiomasRequeridos',
            field=models.ManyToManyField(to='intereses.Idioma'),
        ),
    ]
